# Generated by Django 5.2.1 on 2025-06-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_color_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='usage_count',
        ),
    ]
