# Generated by Django 5.2.1 on 2025-06-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_categories_alter_asset_tags'),
        ('categories', '0001_initial'),
        ('tags', '0002_alter_tag_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='assets', through='assets.AssetCategory', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='assets', through='assets.AssetTag', to='tags.tag'),
        ),
    ]
