# Generated by Django 5.2.1 on 2025-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionasset',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='collection',
            name='color_hex',
            field=models.CharField(blank=True, default='#808080', max_length=7),
        ),
    ]
