# Generated by Django 5.2.1 on 2025-06-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_rename_added_at_collectionasset_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionasset',
            options={},
        ),
        migrations.RenameField(
            model_name='collectionasset',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.RemoveField(
            model_name='collectionasset',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
