# Generated by Django 5.2.1 on 2025-06-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collectionasset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
